### ISSUE TITLE
Foundry-VTT-Spell Power Level Forbidden Lands always rolls Zero

### ISSUE THREAD

**Issue by Ezekiel-2703** [Forbidden-Lands-FVTT/fbl-content-modules#16] opened 2022-09-19 10:27 UTC
Hi,

In the Foundry Forbidden Lands Core Module version 10.0.0-3 when I roll for the spellpower of a spell it always rolls-up zero irrespective of the amount of willpower points I spend. So Even when I put in 10 points it still repeatedly rolls up zero for all spells. Is this a known bug and if so is there a workaround?

Kind regards,

Ezekiel

![Spell Power](https://user-images.githubusercontent.com/113899330/190997653-d8825e54-5fc0-4082-9c12-506b5471aa5a.JPG)
![Spell Power  resultJPG](https://user-images.githubusercontent.com/113899330/190997964-6c3819f9-8546-4d54-b25a-ac3b86631615.JPG)

**Comment by aMediocreDad** [comment] 2022-09-24 20:32
Hi, thanks for submitting this issue.

This is, however, the wrong repository for this submission. The issue is with the core system and should be posted here: https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/issues

That said you do not need to as this is a duplicate of this: https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/issues/249

**Closed as not planned by aMediocreDad** 2022-09-24 20:32 UTC
